### PR TITLE
Enhanced `terraform plan` and `terraform apply` commands

### PR DESCRIPTION
**Pull request by DavidS-ovm**
plan

### CODE REVIEW

**Review by dylanratcliffe — APPROVED** [review]
This is awesome and I'm keen to get this merged, though I think there are some things we can improve:

## Wrapping

We seem to be wrapping at a fixed point regardless of the terminal width which leads to things like the below where the link has been wrapped, but because it was the CLI that wrapped it and not the terminal it messes up the link and when I click it I don't get the whole link

Screenshot 2024-05-02 at 4 52 52 PM

## Authenticate with browser shows >1 time

When I tried locally I was shown the "Authenticate with a browser" more than once, I would have thought that once I had done this once I'd be fine

Screenshot 2024-05-02 at 4 53 59 PM

## Inconsistent when previewing steps

At some stages it seems like we're showing a preview of the next step that is going to happen. Like here it looks like we're currently "Waiting for device auth..." and then next is "Configuring AWS Access":

Screenshot 2024-05-02 at 4 56 36 PM

I don't mind this but if we are going to preview what steps are coming next I think we should be consistent about it i.e. layout the whole process at the start, or just show thw current and past steps

## Does it not wait for risks?

It didn't wait for risks for me, I'm assuming this just isn't done yet?

## Improvement: Can we hide things that serve no purpose after they are done?

For example, all of the text that goes along with auth is useless once you've authenticated. You're not going to want to scroll back and see what it asked you to do. Is it possible to basically collapse this to just a single line like we already have that says authentication successful?

**Comment by DavidS-ovm** [comment]
> This is awesome and I'm keen to get this merged, though I think there are some things we can improve:
> ## Wrapping
> 
> We seem to be wrapping at a fixed point regardless of the terminal width which leads to things like the below where the link has been wrapped, but because it was the CLI that wrapped it and not the terminal it messes up the link and when I click it I don't get the whole link
> Screenshot 2024-05-02 at 4 52 52 PM

Fixed this in https://github.com/overmindtech/cli/pull/246/commits/7e37b8e7cb1c6c252dde3f36a3af11eb66a822bd

> ## Authenticate with browser shows >1 time
> 
> When I tried locally I was shown the "Authenticate with a browser" more than once, I would have thought that once I had done this once I'd be fine
> Screenshot 2024-05-02 at 4 53 59 PM

fixed in https://github.com/overmindtech/cli/pull/246/commits/535d7503190fa2bc54efae55eb9b79a52fca249b : don't display the auth message after the authentication succeeded.

> ## Inconsistent when previewing steps
> 
> At some stages it seems like we're showing a preview of the next step that is going to happen. Like here it looks like we're currently "Waiting for device auth..." and then next is "Configuring AWS Access":
> Screenshot 2024-05-02 at 4 56 36 PM
> 
> I don't mind this but if we are going to preview what steps are coming next I think we should be consistent about it i.e. layout the whole process at the start, or just show thw current and past steps

I've added steps for "Planned Changes" and "Processing" (also update the gif above). This is pretty flexible and we can add and remove tasks to taste.

> ## Does it not wait for risks?
> 
> It didn't wait for risks for me, I'm assuming this just isn't done yet?

I've changed the text on the link to mention risks:
> Check the blast radius graph and risks at <URL>

We can add more waiting and more output after this if you want. My thinking here was that it gives folks something to look at (the graph) while they're waiting for the risk calculation.

> ## Improvement: Can we hide things that serve no purpose after they are done?
> 
> For example, all of the text that goes along with auth is useless once you've authenticated. You're not going to want to scroll back and see what it asked you to do. Is it possible to basically collapse this to just a single line like we already have that says authentication successful?

Yes. See above change.

**Comment by DavidS-ovm** [comment]
(updated the commit links above after rebasing)

**Comment by DavidS-ovm** [comment]
Yeah, please don't think this is the final form of the UI here! This is a
working prototype. It was hard enough to wrap my head around bubbletea's
architecture on the first pass 😂

**Pull request merged**
