### PR TITLE
(feat) display more information about aws creds being used.

### PR DESCRIPTION
**Pull request by tphoney**
https://github.com/overmindtech/cli/issues/591

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
Can I get a preview of what this looks like? Either a copy-paste or an mp4?

**Comment by tphoney** [comment]
> Can I get a preview of what this looks like? Either a copy-paste or an mp4?

**Comment by tphoney** [comment]
> Can I get a preview of what this looks like? Either a copy-paste or an mp4?

https://youtu.be/9od07D42qmo

**Review by dylanratcliffe — APPROVED** [review]
Okay let's get this merged as it's a good improvement, but I still thing there is a fair bit we can do to improve UX i.e.

* Fail silently if we can't open the browser
* Why do we have empty lines between the messages in blue?
* The blue messages don't really help us much. For example we get an error that it can't connect to a certain IP, this doesn't make a whole lot of sense, where did we configure that? The reason of course is that it couldn't find any local config so it defaulted to using in-AWS auth, which doesn't exist since we're not running in AWS, but this isn't show to the user well and will be confusing

**Comment by tphoney** [comment]
> Okay let's get this merged as it's a good improvement, but I still thing there is a fair bit we can do to improve UX i.e.
> 
> * Fail silently if we can't open the browser 
fixed, following what we do on the tf commands, do you want them changed to ?
> * Why do we have empty lines between the messages in blue?
https://github.com/overmindtech/cli/blob/aa1fea9928f986a109370eb3db11df603c3901c1/cmd/explore.go#L51
> * The blue messages don't really help us much. For example we get an error that it can't connect to a certain IP, this doesn't make a whole lot of sense, where did we configure that? The reason of course is that it couldn't find any local config so it defaulted to using in-AWS auth, which doesn't exist since we're not running in AWS, but this isn't show to the user well and will be confusing
the parsing of TF to get config, and the running of the config are in 2 differnent code bases. 
when passing the config we could pass through the file used by config to aws-source and then error better there.

**Comment by tphoney** [comment]
@dylanratcliffe https://youtu.be/V1LUsNN1HpQ

**Comment by dylanratcliffe** [comment]
Looks much nicer

**Pull request merged**
