### PR TITLE
implement revlink warmup before terraform commands; show risks after run

### LINKED ISSUE #290: cli: revlink warmup for new users

### PR DESCRIPTION
**Pull request by DavidS-ovm**
plan

This adds about a minute of wait time with our dogfood environment. I've made it so the revlink warmup runs in parallel to `terraform plan`, which hides a bit of that latency. See the gif above.

Fixes #290, #294

### CODE REVIEW

**Review by dylanratcliffe — COMMENTED** [review]
Having it run in parallel with the plan is brilliant. Are we able to be a bit more intelligent here with how long we wait for the revlink cache? Since we wait for the plan anyway, maybe we could time out say 30s after the plan completes? Most of the time the vast majority of the discovery happens at the beginning with things tailing off towards the end so the changes if us missing something important reduces exponentially (ish) with time, so I think it'd be safe to just decide to move on at some point for the purposes of UX

**Comment by DavidS-ovm** [comment]
> Are we able to be a bit more intelligent here with how long we wait for the revlink cache? Since we wait for the plan anyway, maybe we could time out say 30s after the plan completes? Most of the time the vast majority of the discovery happens at the beginning with things tailing off towards the end so the changes if us missing something important reduces exponentially (ish) with time, so I think it'd be safe to just decide to move on at some point for the purposes of UX

I see a few reasons against that:
1) the only time a user will see that is on the initial run when setting up their account. After that the scheduled job in the backend will ensure revlink caches stay hot and the CLI will just fall through here
2) as it is currently implemented in the backend abandoning the RevlinkWarmup connectrpc request will cancel the work on the server causing RevlinkWarmup to run again on the next CLI call (until a background RevlinkWarmup job finishes successfully)
3) large accounts will likely run into any useful static limit we set, causing them to loop on 2)

**Comment by dylanratcliffe** [comment]
That raises a good point, in that if someone creates an account and only ever uses the CLI, in a week's time their revlink cache will be considered "warm" when actually last time the warmup ran there were almost certainly no sources available and therefore nothing added to the cache. This might require some more thought.. Maybe in a call today if I have time?

**Comment by DavidS-ovm** [comment]
excellent catch. more generally this also applies to any source offline
during warmup, e.g. because of system stability issues. One idea could be
to make warmup-status per-source and track and refresh at this higher
granularity.

**Review by dylanratcliffe — APPROVED** [review]
In that case LGTM with it waiting for it to be done and we'll discuss how we define what "done" actually means later

**Review by dylanratcliffe — APPROVED** [review]
That's great!

**Pull request merged**
