### PR TITLE
Risk style

### PR DESCRIPTION
**Pull request by dylanratcliffe**
Before:

Screenshot 2024-05-30 at 2 23 26 PM

After:

Screenshot 2024-05-30 at 2 22 31 PM

Want to confirm that people actually prefer the new version before I merge

### CODE REVIEW

**Comment by getinnocuous** [comment]
Tbh I prefer the 1st version 😬😆

**Comment by dylanratcliffe** [comment]
@jameslaneovermind @DavidS-ovm Can I get your opinions too when I get a chance?

**Comment by DavidS-ovm** [comment]
I like the simpler symbols of the new version and the bolder colors of the OG

**Comment by jameslaneovermind** [comment]
The symbols are less distracting which I like but I miss the original colours as they are a bit more eye catching.

**Comment by dylanratcliffe** [comment]
Excellent in that case I'm going to the combination of thee two

**Pull request merged**
